### ISSUE TITLE
Is there a way to not add h3 to ToC?

### ISSUE THREAD

**Issue by tboerger** [pages-themes/leap-day#40]
I'm using this nice simple theme for automaitcally generated documentation, this works great so far except for pages the document lots of options, you can see it at https://machippie.github.io/system/.

Is there a way to limit the ToC only to h1 and h2? Or to get a better scrolling behavior for the sidebar?

**Comment by FriedrichWeinmann** [comment]
Hi @tboerger ,

been playing around with this myself and found a way to do this (in a rather convenient manner, too).
Basically, in your own repository create a file like this:
`assets/js/main.js`
Then copy the content from here:
https://github.com/pages-themes/leap-day/blob/master/assets/js/main.js

With that you have a local override of the main.js file and can edit the logic!
(Downside: If this ever gets updated, you don't automatically receive the update)

For example, you can now replace this:
```
$("section h1, section h2, section h3").each(function(){
```
with
```
$("section h1, section h2").each(function(){
```
And thus exclude h3 headers from being included.

**Comment by tboerger** [comment]
Not the most elegant solution, but at least a workaround for that.

**Comment by FriedrichWeinmann** [comment]
btw, I just finished setting up my project, in case you find it useful:

https://github.com/ActiveDirectoryManagementFramework/ActiveDirectoryManagementFramework.github.io

http://admf.one

What I changed from the default template:

- Multiple buttons for the yellow bar
- Changed the auto-indexer for the ul. Instead of content header levels, I read a json file (which will be auto-generated using Azure DevOps as a CI task)
- Moved the ul list to the top of the file if a small screen (e.g.: mobile device) would cause the default version to be hidden. (See my modified default.html for that. The second ul gets modified as part of the main.js)

The only files I needed to touch for all that were default.html and main.js.
